# Google Cloud Build configuration for Next.js frontend
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/poc-intake-frontend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/poc-intake-frontend:latest',
      '.'
    ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/poc-intake-frontend:$BUILD_ID'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/poc-intake-frontend:latest'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'poc-intake-frontend',
      '--image', 'gcr.io/$PROJECT_ID/poc-intake-frontend:$BUILD_ID',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--port', '3000',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--timeout', '300',
      '--set-env-vars', 'NODE_ENV=production'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/poc-intake-frontend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/poc-intake-frontend:latest'